### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by PeterBell**
Hey @1point618 would you check this out?

### CODE REVIEW

**Comment by githubteacher** [comment]
Hmm, you forgot to include the project name @PeterBell

**Comment by githubteacher** [comment]
LGTM :+1:

**Comment by githubteacher** [comment]
colbert

**Comment by 1point618** [comment]
Sure thing @PeterBell ! Is there a good place to start? Not sure where to find info about what it is :smile:

**Pull request merged**
